apiVersion: apps/v1
kind: Deployment
metadata:
  name: gettaskapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gettaskapp
  template:
    metadata:
      labels:
        app: gettaskapp
    spec:
      containers:
      - name: gettaskapp
        image: gettaskapp:latest
        ports:
        - containerPort: 8080
        livenessProbe:         
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:          
          httpGet:
            path: /readiness
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 1    

